### ISSUE TITLE
Issues using Spotify.

### ISSUE THREAD

**Issue by binary-blazer** [topi314/LavaSrc#113]
<details>
  <summary style="font-size: 20px; font-weight: bold; cursor: pointer; background: opacity: 0.5; color: #fff; padding: 10px; border: 1px solid #fff; border-radius: 5px; margin-top: 10px;">
     Issue
 </summary>

  Once my discord bot tries to search a song on the lavalink server it returns the error message:
  ```
  [ ERROR ] Error: Lavalink Node SearchQuerySource: 'spotify' is not available
  ```
</details>

<details>
  <summary style="font-size: 20px; font-weight: bold; cursor: pointer; background: opacity: 0.5; color: #fff; padding: 10px; border: 1px solid #fff; border-radius: 5px; margin-top: 10px;">
     application.yml
 </summary>

  ```yaml
  lavalink:
    server:
        bufferDurationMs: 400
        frameBufferDurationMs: 5000
        gc-warnings: true
        opusEncodingQuality: 0
        password: youshallnotpass
        playerUpdateInterval: 5
        resamplingQuality: LOW
        soundcloudSearchEnabled: true
        sources:
            bandcamp: true
            http: true
            local: false
            mixer: true
            soundcloud: true
            spotify: true
            twitch: true
            vimeo: true
            youtube: false
        trackStuckThresholdMs: 10000
        useSeekGhosting: true
        youtubePlaylistLoadLimit: 6
        youtubeSearchEnabled: true
logging:
    file:
        max-history: 30
        max-size: 1GB
    level:
        lavalink: INFO
        root: INFO
    path: ./logs/
    request:
        enabled: true
        includeClientInfo: true
        includeHeaders: false
        includePayload: true
        includeQueryString: true
        maxPayloadLength: 10000
metrics:
    prometheus:
        enabled: false
        endpoint: /metrics
plugins:
    lavasrc:
        applemusic:
            albumLoadLimit: 6
            countryCode: US
            mediaAPIToken: '...'
            playlistLoadLimit: 6
        deezer:
            masterDecryptionKey: your master decryption key
        flowerytts:
            audioFormat: mp3
            silence: 0
            speed: 1
            translate: false
            voice: default voice
        providers:
            - ytsearch:"%ISRC%"
            - ytsearch:%QUERY%
        sources:
            applemusic: false
            deezer: false
            flowerytts: false
            spotify: true
            yandexmusic: false
            youtube: false
        spotify:
            albumLoadLimit: 6
            clientId: "my client id"
            clientSecret: "my client secret"
            countryCode: US
            playlistLoadLimit: 6
        yandexmusic:
            accessToken: your access token
sentry:
    dsn: ""
    environment: ""
server:
    address: 0.0.0.0
    port: 3030
  ```
</details>

I have tried everything explained here: https://github.com/topi314/LavaSrc/tree/v3-legacy#lavalink-usage
can someone help me?
